### POST SELECT - 코드 리스트 조회
GET http://localhost:8080/api/members/me
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwibmlja25hbWUiOiLthYzsiqTthLAiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTc3NzM3MTc2MiwiZXhwIjoxNzc3Mzc1MzYyfQ.3oRWKPSe5LwBYEaWP3yImvPrHKNpmI36pb84G7mmS39vU4dxyZKfi3_SLC3lEAgE